version: '3.7'
services:

  redis:
    image: redis
    container_name:
      redis
    ports:
      - "6379:6379"

  bot:
    build:
      context: .
    container_name:
      oguzok
    env_file:
      - .env
